apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrpoject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myrpoject
  template:
    metadata:
      labels:
        app: myrpoject
    spec:
      containers:
        - name: myrpoject
          image: hariharanbharatha/myrpoject-pipeline:1.0.0-13
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
